using System.Globalization;
using System.Text;

namespace Bmfontier.Cli.Config;

/// <summary>
/// Serializes <see cref="CliOptions"/> to .bmfc INI format.
/// </summary>
internal static class BmfcWriter
{
    public static void Write(CliOptions options, string filePath)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# bmfontier configuration file");
        sb.AppendLine($"# Generated by: bmfontier generate --save-config");
        sb.AppendLine($"# Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();

        // [font]
        sb.AppendLine("[font]");
        if (options.FontPath != null)
            sb.AppendLine($"path = {options.FontPath}");
        else
            sb.AppendLine("# path = fonts/MyFont.ttf");

        if (options.SystemFontName != null)
            sb.AppendLine($"system-font = {options.SystemFontName}");
        else
            sb.AppendLine("# system-font = Arial");

        if (options.FaceIndex != 0)
            sb.AppendLine($"face-index = {options.FaceIndex}");
        else
            sb.AppendLine("# face-index = 0");

        sb.AppendLine();

        // [rendering]
        sb.AppendLine("[rendering]");
        sb.AppendLine($"size = {options.Size ?? 32}");
        WriteValue(sb, "dpi", options.Dpi.ToString(), options.Dpi != 72);
        WriteValue(sb, "anti-alias", options.AntiAlias.ToString().ToLowerInvariant(),
            options.AntiAlias != AntiAliasMode.Grayscale);
        WriteValue(sb, "sdf", options.Sdf.ToString().ToLowerInvariant(), options.Sdf);
        WriteValue(sb, "bold", options.Bold.ToString().ToLowerInvariant(), options.Bold);
        WriteValue(sb, "italic", options.Italic.ToString().ToLowerInvariant(), options.Italic);
        sb.AppendLine();

        // [characters]
        sb.AppendLine("[characters]");
        if (options.CharsetPreset != null)
            sb.AppendLine($"preset = {options.CharsetPreset}");
        WriteValue(sb, "chars", options.ExplicitChars, options.ExplicitChars != null);
        WriteValue(sb, "chars-file", options.CharsFilePath, options.CharsFilePath != null);
        if (options.UnicodeRanges.Count > 0)
        {
            var ranges = string.Join(", ",
                options.UnicodeRanges.Select(r => $"{r.Start:X4}-{r.End:X4}"));
            sb.AppendLine($"ranges = {ranges}");
        }
        else
        {
            sb.AppendLine("# ranges = 0020-007E, 0400-04FF");
        }
        sb.AppendLine();

        // [atlas]
        sb.AppendLine("[atlas]");
        sb.AppendLine($"max-texture-size = {options.MaxTextureSize}");
        var pad = options.Padding;
        if (pad.Up == pad.Right && pad.Right == pad.Down && pad.Down == pad.Left)
            sb.AppendLine($"padding = {pad.Up}");
        else
            sb.AppendLine($"padding = {pad.Up},{pad.Right},{pad.Down},{pad.Left}");

        var spc = options.Spacing;
        if (spc.Horizontal == spc.Vertical)
            sb.AppendLine($"spacing = {spc.Horizontal}");
        else
            sb.AppendLine($"spacing = {spc.Horizontal},{spc.Vertical}");

        sb.AppendLine($"power-of-two = {(options.PowerOfTwo ?? true).ToString().ToLowerInvariant()}");
        sb.AppendLine($"packer = {(options.PackingAlgorithm == PackingAlgorithm.MaxRects ? "maxrects" : "skyline")}");
        WriteValue(sb, "channel-pack", options.ChannelPacking.ToString().ToLowerInvariant(), options.ChannelPacking);
        sb.AppendLine();

        // [effects]
        sb.AppendLine("[effects]");
        WriteValue(sb, "outline", options.Outline.ToString(), options.Outline > 0);
        WriteValue(sb, "gradient-top", options.GradientTop, options.GradientTop != null);
        WriteValue(sb, "gradient-bottom", options.GradientBottom, options.GradientBottom != null);
        sb.AppendLine();

        // [kerning]
        sb.AppendLine("[kerning]");
        sb.AppendLine($"enabled = {(options.Kerning ?? true).ToString().ToLowerInvariant()}");
        sb.AppendLine();

        // [variable]
        sb.AppendLine("[variable]");
        if (options.VariationAxes.Count > 0)
        {
            foreach (var (tag, val) in options.VariationAxes)
                sb.AppendLine($"{tag} = {val.ToString(CultureInfo.InvariantCulture)}");
        }
        else
        {
            sb.AppendLine("# wght = 700");
            sb.AppendLine("# wdth = 75");
        }
        sb.AppendLine();

        // [output]
        sb.AppendLine("[output]");
        sb.AppendLine($"format = {options.OutputFormat.ToString().ToLowerInvariant()}");
        WriteValue(sb, "path", options.OutputPath, options.OutputPath != null);

        var dir = Path.GetDirectoryName(Path.GetFullPath(filePath));
        if (!string.IsNullOrEmpty(dir))
            Directory.CreateDirectory(dir);
        File.WriteAllText(filePath, sb.ToString());
    }

    private static void WriteValue(StringBuilder sb, string key, string? value, bool active)
    {
        if (active && value != null)
            sb.AppendLine($"{key} = {value}");
        else
            sb.AppendLine($"# {key} = {value ?? ""}");
    }
}
